<a href="https://colab.research.google.com/github/archakrishnan7/Data-From-Different-Resources-Case-Study/blob/main/Data_from_diff_resources_case_study.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PART A - DATA EXTRACTION

In [1]:
import pandas as pd

TASK 1

In [3]:
# reading csv file
population = pd.read_csv('/content/population.csv')
population.head(5)

         country  population
0  United States   331002651
1          China  1411778724
2          India  1380004385
3          Japan   125836021
4        Germany    83240525

In [5]:
population.shape

(25, 2)

In [7]:
print(population.dtypes)

country       object
population     int64
dtype: object

TASK 2

In [8]:
# reading excel file
gdp = pd.read_excel('/content/gdp.xlsx')
gdp

           Country       GDP
0    United States  30500000
1            China  19230000
2            India   4187000
3            Japan   4180000
4          Germany   4744000
5   United Kingdom   3839000
6           France   3211000
7            Italy   2420000
8           Canada   2250000
9        Australia   1880000
10          Brazil   2330000
11          Russia   2200000
12     South Korea   1800000
13           Spain   1710000
14          Mexico   1810000
15       Indonesia   1500000
16    Saudi Arabia   1100000
17          Turkey   1350000
18    South Africa    410000
19       Argentina    640000
20     Netherlands   1150000
21     Switzerland    940000
22          Sweden    650000
23          Norway    580000
24       Singapore    530000

In [9]:
print(gdp.columns)

Index(['Country', 'GDP'], dtype='object')

In [10]:
print(gdp.dtypes)

Country    object
GDP         int64
dtype: object

TASK 3

In [14]:
# reading json file
internet_users = pd.read_json('/content/internet_users.json')
internet_users

           country  internet_users
0    United States       312000000
1            China      1080000000
2            India       850000000
3            Japan       118000000
4          Germany        79000000
5   United Kingdom        66000000
6           France        62000000
7            Italy        56000000
8           Canada        36000000
9        Australia        24000000
10          Brazil       181000000
11          Russia       125000000
12     South Korea        50000000
13           Spain        44000000
14          Mexico       102000000
15       Indonesia       212000000
16    Saudi Arabia        34000000
17          Turkey        69000000
18    South Africa        43000000
19       Argentina        41000000
20     Netherlands        17000000
21     Switzerland         8500000
22          Sweden        10100000
23          Norway         5300000
24       Singapore         5600000

In [17]:
internet_users = pd.read_json('/content/internet_users.json')
print(internet_users)

           country  internet_users
0    United States       312000000
1            China      1080000000
2            India       850000000
3            Japan       118000000
4          Germany        79000000
5   United Kingdom        66000000
6           France        62000000
7            Italy        56000000
8           Canada        36000000
9        Australia        24000000
10          Brazil       181000000
11          Russia       125000000
12     South Korea        50000000
13           Spain        44000000
14          Mexico       102000000
15       Indonesia       212000000
16    Saudi Arabia        34000000
17          Turkey        69000000
18    South Africa        43000000
19       Argentina        41000000
20     Netherlands        17000000
21     Switzerland         8500000
22          Sweden        10100000
23          Norway         5300000
24       Singapore         5600000

TASK 4

In [18]:
# reading xml file
literacy_rate = pd.read_xml('/content/literacy_rate.xml')
literacy_rate

              name  literacy_rate
0    United States           99.0
1            China           97.2
2            India           77.7
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

In [19]:
literacy_rate = pd.read_xml('/content/literacy_rate.xml')
print(literacy_rate)

              name  literacy_rate
0    United States           99.0
1            China           97.2
2            India           77.7
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

Part B -DATA UNDERSTANDING

TASK 5
Explore each dataset.
Find the following:
● Number of rows
● Number of columns
● Column names
● Data types
● Missing values
● Duplicate records

In [20]:
def explore_dataset(df, name):
    print(f"\n--- {name} ---")
    print("Shape (rows, columns):", df.shape)
    print("Column names:", df.columns.tolist())
    print("Data types:\n", df.dtypes)
    print("Missing values:\n", df.isnull().sum())
    print("Duplicate rows:", df.duplicated().sum())

# Explore all datasets
explore_dataset(gdp, "Excel Dataset")
explore_dataset(population, "CSV Dataset")
explore_dataset(internet_users, "JSON Dataset")
explore_dataset(literacy_rate, "XML Dataset")

--- Excel Dataset ---
Shape (rows, columns): (25, 2)
Column names: ['Country', 'GDP']
Data types:
 Country    object
GDP         int64
dtype: object
Missing values:
 Country    0
GDP        0
dtype: int64
Duplicate rows: 0

--- CSV Dataset ---
Shape (rows, columns): (25, 2)
Column names: ['country', 'population']
Data types:
 country       object
population     int64
dtype: object
Missing values:
 country       0
population    0
dtype: int64
Duplicate rows: 0

--- JSON Dataset ---
Shape (rows, columns): (25, 2)
Column names: ['country', 'internet_users']
Data types:
 country           object
internet_users     int64
dtype: object
Missing values:
 country           0
internet_users    0
dtype: int64
Duplicate rows: 0

--- XML Dataset ---
Shape (rows, columns): (25, 2)
Column names: ['name', 'literacy_rate']
Data types:
 name              object
literacy_rate    float64
dtype: object
Missing values:
 name             0
literacy_rate    0
dtype: int64
Duplicate rows: 0

Part C - DATA TRANSFORMATION

TASK 6

In [21]:
gdp = gdp.rename(columns={'Country':'country'})
literacy_rate = literacy_rate.rename(columns={'name':'country'})

In [22]:
set(gdp['country']) == set(internet_users['country']) == set(population['country']) == set(literacy_rate['country'])

True

TASK 7

In [23]:
population['population'] = pd.to_numeric(population['population'])
gdp['GDP'] = pd.to_numeric(gdp['GDP'])
internet_users['internet_users'] = pd.to_numeric(internet_users['internet_users'])
literacy_rate['literacy_rate'] = pd.to_numeric(literacy_rate['literacy_rate'])


print("Population dtype:", population['population'].dtype)
print("GDP dtype:", gdp['GDP'].dtype)
print("Internet Users dtype:", internet_users['internet_users'].dtype)
print("Literacy Rate dtype:", literacy_rate['literacy_rate'].dtype)

Population dtype: int64
GDP dtype: int64
Internet Users dtype: int64
Literacy Rate dtype: float64

TASK 8

In [24]:
merged_data = population.merge(gdp, on='country') \
                             .merge(internet_users, on='country') \
                             .merge(literacy_rate, on='country')

merged_data.head()

         country  population       GDP  internet_users  literacy_rate
0  United States   331002651  30500000       312000000           99.0
1          China  1411778724  19230000      1080000000           97.2
2          India  1380004385   4187000       850000000           77.7
3          Japan   125836021   4180000       118000000           99.0
4        Germany    83240525   4744000        79000000           99.0

TASK 9

In [27]:
merged_data["Internet_penetration(%)"] = round((merged_data["internet_users"] / merged_data["population"]) * 100,2)
merged_data["GDP_per_capita"] = round(merged_data["GDP"] / merged_data["population"],2)
merged_data.head()

,country,population,GDP,internet_users,literacy_rate,Internet_penetration(%),GDP_per_capita
0,United States,331002651,30500000,312000000,99.0,94.26,0.09
1,China,1411778724,19230000,1080000000,97.2,76.50,0.01
2,India,1380004385,4187000,850000000,77.7,61.59,0.00
3,Japan,125836021,4180000,118000000,99.0,93.77,0.03
4,Germany,83240525,4744000,79000000,99.0,94.91,0.06

PART D - LOAD DATA

TASK 10

In [30]:
import sqlite3
conn = sqlite3.connect('country_data.db')
merged_data.to_sql("country_statistics",conn,if_exists="replace",index=False)
print("Database and 'country_statistics' table succesfully")

Database and 'country_statistics' table succesfully

TASK 11

In [33]:
merged_check = pd.read_sql("select * from country_statistics limit 5", conn)
print(merged_check)

         country  population       GDP  internet_users  literacy_rate  \
0  United States   331002651  30500000       312000000           99.0
1          China  1411778724  19230000      1080000000           97.2
2          India  1380004385   4187000       850000000           77.7
3          Japan   125836021   4180000       118000000           99.0
4        Germany    83240525   4744000        79000000           99.0

   Internet_penetration(%)  GDP_per_capita
0                    94.26            0.09
1                    76.50            0.01
2                    61.59            0.00
3                    93.77            0.03
4                    94.91            0.06

PART E -DATA ANALYSIS USING PANDAS

In [34]:
#1  List the Top 5 countries by GDP.
top5_gdp = merged_data.sort_values(by="GDP", ascending=False).head(5)
print(top5_gdp[["country","GDP"]])

         country       GDP
0  United States  30500000
1          China  19230000
4        Germany   4744000
2          India   4187000
3          Japan   4180000

In [35]:
#2 List the Top 5 countries by population.
top_population = merged_data.sort_values(by="population",ascending=False).head(5)
print(top_population[["country","population"]])

          country  population
1           China  1411778724
2           India  1380004385
0   United States   331002651
15      Indonesia   273523615
10         Brazil   212559417

In [36]:
#3 Calculate the average literacy rate.
average_literacy = merged_data["literacy_rate"].mean().round(2)
print("Average Literacy Rate:", average_literacy)

Average Literacy Rate: 97.25

In [37]:
#4  List all countries having a literacy rate greater than 90%.
high_literacy = merged_data[merged_data["literacy_rate"] > 90]
print(high_literacy[["country", "literacy_rate"]])

           country  literacy_rate
0    United States           99.0
1            China           97.2
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

In [39]:
#5 List all countries having an internet penetration greater than 70%.
high_internet = merged_data[merged_data["Internet_penetration(%)"] > 70]
print(high_internet[["country", "Internet_penetration(%)"]])

           country  Internet_penetration(%)
0    United States                    94.26
1            China                    76.50
3            Japan                    93.77
4          Germany                    94.91
5   United Kingdom                    97.22
6           France                    94.98
7            Italy                    92.62
8           Canada                    94.72
9        Australia                    93.43
10          Brazil                    85.15
11          Russia                    85.65
12     South Korea                    96.56
13           Spain                    94.11
14          Mexico                    79.11
15       Indonesia                    77.51
16    Saudi Arabia                    97.66
17          Turkey                    81.81
18    South Africa                    72.50
19       Argentina                    90.72
20     Netherlands                    97.47
21     Switzerland                    98.21
22          Sweden                    97.55
23          Norway                    97.76
24       Singapore                    95.72

In [41]:
#6 List the Top 5 countries by GDP per capita.
top5_gdp_per_capita = merged_data.sort_values(by="GDP_per_capita", ascending=False).head(5)
print(top5_gdp_per_capita[["country", "GDP_per_capita"]])

          country  GDP_per_capita
21    Switzerland            0.11
23         Norway            0.11
24      Singapore            0.09
0   United States            0.09
9       Australia            0.07

In [42]:
#7 Calculate the total population represented in the dataset.
total_population = merged_data["population"].sum()
print("Total Population in Dataset:", total_population)

Total Population in Dataset: 4720039725

In [43]:
#8 Calculate the average internet penetration across all countries.
average_internet_penetration = merged_data["Internet_penetration(%)"].mean().round(2)
print("Average Internet Penetration (%):", average_internet_penetration)

Average Internet Penetration (%): 89.66

In [44]:
#9 Identify the country having the highest number of internet users.
max_internet_users = merged_data.loc[merged_data["internet_users"].idxmax()]
print("Country with highest internet users:", max_internet_users["country"])
print("Number of internet users:", max_internet_users["internet_users"])

Country with highest internet users: China
Number of internet users: 1080000000

In [45]:
#10  Find the correlation between Literacy Rate and Internet Penetration.
correlation = merged_data["literacy_rate"].corr(merged_data["Internet_penetration(%)"])
print("Correlation between Literacy Rate and Internet Penetration:", round(correlation, 2))

Correlation between Literacy Rate and Internet Penetration: 0.77

PART F - DATA ANALYSIS USING SQL

In [46]:
#11 Display the Top 5 countries by GDP.
query = """select country, GDP from country_statistics order by GDP desc limit 5;"""
top5_gdp = pd.read_sql(query, conn)
print(top5_gdp)

         country       GDP
0  United States  30500000
1          China  19230000
2        Germany   4744000
3          India   4187000
4          Japan   4180000

In [47]:
#12 Find the average literacy rate.
query = """SELECT ROUND(AVG(literacy_rate), 2) AS Average_Literacy_Rate FROM country_statistics;"""
avg_literacy = pd.read_sql(query, conn)
print(avg_literacy)

   Average_Literacy_Rate
0                  97.25

In [49]:
#13 Display all countries having literacy rate above 90%.
query = """SELECT country, literacy_rate FROM country_statistics WHERE literacy_rate > 90 ORDER BY literacy_rate DESC;"""
high_literacy = pd.read_sql(query, conn)
print(high_literacy)

           country  literacy_rate
0           Norway          100.0
1           Russia           99.7
2        Argentina           99.1
3    United States           99.0
4            Japan           99.0
5          Germany           99.0
6   United Kingdom           99.0
7           France           99.0
8            Italy           99.0
9           Canada           99.0
10       Australia           99.0
11     Netherlands           99.0
12     Switzerland           99.0
13          Sweden           99.0
14     South Korea           98.8
15           Spain           98.6
16       Singapore           97.5
17    Saudi Arabia           97.3
18           China           97.2
19          Turkey           96.7
20       Indonesia           96.0
21          Mexico           95.4
22    South Africa           95.0
23          Brazil           93.2

In [50]:
#14 Find the Top 5 countries with the highest internet penetration.
top5_internet = merged_data.sort_values(by="Internet_penetration(%)", ascending=False).head(5)
print(top5_internet[["country", "Internet_penetration(%)"]])

         country  Internet_penetration(%)
21   Switzerland                    98.21
23        Norway                    97.76
16  Saudi Arabia                    97.66
22        Sweden                    97.55
20   Netherlands                    97.47

In [51]:
#15 Calculate the total population.
total_population = merged_data["population"].sum()
print("Total Population in Dataset:", total_population)

Total Population in Dataset: 4720039725

In [52]:
#16 Find the country with the highest GDP per capita.
highest_gdp_per_capita = merged_data.loc[merged_data["GDP_per_capita"].idxmax()]
print("Country with highest GDP per capita:", highest_gdp_per_capita["country"])
print("GDP per capita:", highest_gdp_per_capita["GDP_per_capita"])

Country with highest GDP per capita: Switzerland
GDP per capita: 0.11

In [53]:
#17 Export the final merged dataset as a CSV file.
merged_data.to_csv("final_dataset.csv", index=False)
print("Dataset exported successfully as final_dataset.csv")

Dataset exported successfully as final_dataset.csv

In [55]:
#18 Sort the dataset in descending order of GDP per Capita and display the Top 10 countries.
top10_gdp_per_capita = merged_data.sort_values(by="GDP_per_capita", ascending=False).head(10)
print(top10_gdp_per_capita[["country", "GDP_per_capita"]])

           country  GDP_per_capita
21     Switzerland            0.11
23          Norway            0.11
24       Singapore            0.09
0    United States            0.09
9        Australia            0.07
20     Netherlands            0.07
4          Germany            0.06
8           Canada            0.06
5   United Kingdom            0.06
22          Sweden            0.06